env: "dev"

storage_path: "./storage/ss.db"

token_ttl: 1h

grpc:
  port: 44044
  timeout: 10m

storage:
  server: TRAMPAMPAM\SQL2017
  host: TRAMPAMPAM
  path: SQL2017
  port: 0
  database: integ01
  username: admingo
  password: admingo

storage_procedure:
  name_sp: "[dbo].[BOT_AdminChat_Dismissed@check]"
  name_param: "telegram_id"
  tvp_type: "dbo.TvpBigInt"

login:
  name: auditor
  password: auditor